name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate OAuth Metadata
        run: node scripts/generate-metadata.js
        env:
          VITE_BASE_URL: https://igrir.github.io

      - name: Build
        run: npm run build
        env:
          VITE_BASE_URL: https://igrir.github.io
          VITE_BASE_PATH: /

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
